export const PROJECTS_REQUEST = 'PROJECTS_REQUEST';
export const PROJECTS_SUCCEEDED = 'PROJECTS_SUCCEEDED';
export const PROJECTS_FAILED = 'PROJECTS_FAILED';

export const ADD_PROJECT_REQUEST = 'ADD_PROJECT_REQUEST';
export const ADD_PROJECT_SUCCEEDED = 'ADD_PROJECT_SUCCEEDED';
export const ADD_PROJECT_FAILED = 'ADD_PROJECT_FAILED';

export const SET_SELECTED_PROJECT_ID = 'SET_SELECTED_PROJECT_ID';
